project_id = "demffiwvsqmbqvytwesh"

[functions.ai-coach]
verify_jwt = true

[functions.stt-coach]
verify_jwt = true

[functions.tts-coach]
verify_jwt = true

[functions.generate-workout]
verify_jwt = false
